---
# defaults file for install-sysdig-agent
sysdig_agent_namespace: sysdig-agent
agent_version: latest
ansible_python_interpreter: /usr/bin/python3
custom_configuration: 
# Resources needed are subjective to the actual workload.
# Please refer to Sysdig Support for more info.
# See also: https://docs.sysdig.com/en/tuning-sysdig-agent.html
resources_requests_cpu: 1000m
resources_requests_memory: 1024Mi
resources_limits_cpu: 1000m
resources_limits_memory: 1024Mi
# Node Image Analyzer default variables
nia_enabled: False
nia_version: latest